CREATE SCHEMA INOVATECH;
USE INOVATECH;

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT PRIMARY KEY,
NOME_CLIENTE VARCHAR(100) NOT NULL,
CPF_CLIENTE VARCHAR(20) NOT NULL,
TELEFONE_CLIENTE VARCHAR(13) NOT NULL,
DATANASC_CLIENTE VARCHAR(10) NOT NULL,
STATUSFIDELIDADE_CLIENTE VARCHAR(100) NOT NULL,
CEP_CLIENTE VARCHAR(50) NOT NULL,
RUA_CLIENTE VARCHAR(50) NOT NULL,
NUMCASA_CLIENTE VARCHAR(5) NOT NULL,
BAIRRO_CLIENTE VARCHAR(40) NOT NULL,
IDADE_CLIENTE VARCHAR(3) NOT NULL,
UF_CLIENTE CHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
ID_PRODUTO INT PRIMARY KEY,
CATEGORIA_PRODUTO VARCHAR(45) NOT NULL,
QUANTIDADEESTOQUE_PRODUTO VARCHAR(20) NOT NULL,
PREÇO_PRODUTO VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORNECEDOR INT PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(100) NOT NULL,
TELEFONE_FORNECEDOR VARCHAR(13) NOT NULL,
CPF_FORNECEDOR VARCHAR(20) NOT NULL,
EMAIL_FORNECEDOR VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDAS(
ID_VENDA INT PRIMARY KEY,
VALOR_VENDA VARCHAR(45) NOT NULL,
ID_CLIENTE INT,
CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
FORMA_PAGAMENTO INT PRIMARY KEY,
DATA_PAGAMENTO DATE NOT NULL,
VALOR_PAGAMENTO VARCHAR(45) NOT NULL,
STATUS_PAGAMENTO VARCHAR(30) NOT NULL,
ID_VENDA INT,
CONSTRAINT FK_ID_VENDA FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID_VENDA)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_VENDAS(
ID_PRODUTO INT,
ID_VENDA INT, 
CONSTRAINT FK_ID_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
CONSTRAINT FK_ID_VENDA2 FOREIGN KEY(ID_VENDA) REFERENCES VENDAS(ID_VENDA),
QNTDPRODUTO_VENDA VARCHAR(30),
PRIMARY KEY(ID_PRODUTO, ID_VENDA)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_FORNECEDORES(
ID_PRODUTO INT,
ID_FORNECEDOR INT, 
CONSTRAINT ID_PRODUTO2 FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
CONSTRAINT ID_FORNECEDOR FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR),
PRIMARY KEY(ID_PRODUTO, ID_FORNECEDOR)
);

-- COMANDOS DDL

-- Criar Index
CREATE INDEX idx_nome_empresa 
ON Fornecedor (nome_empresa);

-- Criar View
CREATE VIEW vista_fornecedore AS
SELECT nome_empresa, endereco_empresa
FROM Fornecedor;

-- Comando Alter ADD
ALTER TABLE Fornecedores ADD email VARCHAR(100);
-- Comando Alter DROP COLUMUN
ALTER TABLE Fornecedores DROP COLUMN email;
-- Comando Alter MODIFY COLUMN 
ALTER TABLE Fornecedores MODIFY COLUMN email VARCHAR(150);
-- Comando Alter CHANGE COLUMN
ALTER TABLE Fornecedores CHANGE COLUMN email email_completo VARCHAR(150);
-- Comando Alter ADD INDEX
ALTER TABLE Fornecedores ADD INDEX idx_email (email_completo);

-- Remover Banco de Dados:
DROP DATABASE cadeia_de_suprimentos;
-- Remover Tabela:
DROP TABLE Fornecedores;
-- Remover Índice:
DROP INDEX idx_email ON Fornecedores;
-- Remover Visão:
DROP VIEW vista_fornecedore;

-- Remover dados
TRUNCATE TABLE Fornecedores;

-- Alterar nome da tabela
RENAME TABLE Fornecedores TO Fornecedor;

-- Comentarios nas tabelas
ALTER TABLE Fornecedores COMMENT = 'Tabela de informações dos Fornecedores';

-- Adicionar Comentário a Coluna:
ALTER TABLE Fornecedores MODIFY email_completo VARCHAR(150) COMMENT 'email do contato que representa o fornecedor';
